version: "2"
run:
  concurrency: 4
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    funlen:
      lines: 80
      statements: 50
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
    lll:
      line-length: 120
    misspell:
      locale: US
    nestif:
      min-complexity: 4
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      max-open-files: 2048
      severity: warning
      enable-all-rules: false
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocognit
          - gocyclo
          - gosec
          - lll
          - mnd
        path: _test\.go
      - linters:
          - errcheck
          - gosec
          - mnd
          - gocyclo
        path: examples/
      - linters:
          - mnd
        text: 'Magic number: (80|443|8080|3000|5000)'
      - linters:
          - mnd
        text: 'Magic number: (1024|2048|4096|8192)'
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: exported (type|method|function) (.+) should have comment or be unexported
      - path: (.+)\.go$
        text: 'ST1000: at least one file in a package should have a package comment'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/thinkdoggie/zmq4chan
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
