# Defines the configuration version.
# The only possible value is "2".
version: "2"

run:
  timeout: 5m
  go: "1.21"

linters:
  # Default set of linters (replaces disable-all: true)
  default: none
  
  enable:
    - bodyclose
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck  # merges gosimple, staticcheck, stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 120
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - wrapperFunc
        - dupImport # https://github.com/go-critic/go-critic/issues/845
    funlen:
      lines: 100
      statements: 50

  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - funlen
      # Exclude known linters from partially hard-to-fix issues
      - linters:
          - lll
        source: "^//go:generate "

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

  settings:
    goimports:
      local-prefixes: github.com/thinkdoggie/zmq4chan
    gofumpt:
      extra-rules: true

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0 