run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  dupl:
    threshold: 100
  
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
  
  funlen:
    lines: 100
    statements: 50
  
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/zeromq/zmq4chan)
    skip-generated: true
  
  gocyclo:
    min-complexity: 15
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/zeromq/zmq4chan
  
  golint:
    min-confidence: 0.8
  
  gomnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers: 0,1,2,8,10,16,32,64,100,1000,1024
  
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  
  lll:
    line-length: 120
  
  maligned:
    suggest-new: true
  
  misspell:
    locale: US
    ignore-words:
      - cancelled
  
  nakedret:
    max-func-lines: 30
  
  nestif:
    min-complexity: 4
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  revive:
    min-confidence: 0.8
    rules:
      - name: atomic
      - name: line-length-limit
        arguments: [120]
      - name: argument-limit
        arguments: [8]
      - name: cyclomatic
        arguments: [15]
      - name: max-public-structs
        arguments: [10]
      - name: file-header
        disabled: true
  
  staticcheck:
    go: "1.19"
    checks: ["all"]
  
  stylecheck:
    go: "1.19"
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
  
  testpackage:
    skip-regexp: (export|internal)_test\.go
  
  unparam:
    check-exported: false
  
  unused:
    go: "1.19"
  
  whitespace:
    multi-if: false
    multi-func: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - noctx
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - scopelint
        - lll
    
    # Exclude known linter issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    
    # Exclude shadow declarations that are OK
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
    
    # Exclude some staticcheck messages
    - text: "SA9003:"
      linters:
        - staticcheck
    
    # Exclude lll issues for long lines with go:generate
    - source: "^//go:generate "
      linters:
        - lll
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false 